import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const ASX_COMPANIES = [
  // TIER 1: Top 50 ASX Companies (Market Cap Leaders)
  {
    name: 'Google Australia',
    industry: 'Technology',
    sector: 'Software & Services',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.google.com.au',
    fundingCapacity: 'High',
    csrFocus: 'AI Education, Digital Skills, STEM',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Future of Communication']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Amazon Australia',
    industry: 'Technology',
    sector: 'E-commerce & Cloud',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.amazon.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Tech Skills, Innovation, Sustainability',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Future of Communication']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Microsoft Australia',
    industry: 'Technology',
    sector: 'Software & Services',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.microsoft.com/en-au',
    fundingCapacity: 'High',
    csrFocus: 'Tech Education, Youth Skills, AI',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Future of Communication']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Apple Australia',
    industry: 'Technology',
    sector: 'Hardware & Software',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.apple.com',
    fundingCapacity: 'High',
    csrFocus: 'Innovation, Design, Education',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Future of Communication']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Commonwealth Bank',
    industry: 'Finance',
    sector: 'Finance',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.commbank.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Financial Literacy, Youth Programs, Community',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development', 'Future of Communication']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'ANZ Banking Group',
    industry: 'Finance',
    sector: 'Finance',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.anz.com',
    fundingCapacity: 'High',
    csrFocus: 'Financial Inclusion, Skills Development, Community',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development', 'Health']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Westpac Banking',
    industry: 'Finance',
    sector: 'Finance',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.westpac.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Financial Literacy, Indigenous Education, Community',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development', 'Health']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'National Australia Bank',
    industry: 'Finance',
    sector: 'Finance',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.nab.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Financial Inclusion, Youth Employment, Community',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development', 'Intelligence']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Telstra',
    industry: 'Telecommunications',
    sector: 'Telecommunications',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.telstra.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Digital Skills, Tech Education, Connectivity',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Future of Communication']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Woolworths Group',
    industry: 'Retail & Consumer',
    sector: 'Retail',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.woolworthsgroup.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Community, Sustainability, Youth Employment',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Coles Group',
    industry: 'Retail & Consumer',
    sector: 'Retail',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.colesgroup.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Community, Sustainability, Food Security',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'BHP Group',
    industry: 'Mining & Energy',
    sector: 'Energy',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.bhpgroup.com',
    fundingCapacity: 'High',
    csrFocus: 'STEM Education, Sustainability, Indigenous Programs',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Engineering', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Rio Tinto',
    industry: 'Mining & Energy',
    sector: 'Energy',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.riotinto.com',
    fundingCapacity: 'High',
    csrFocus: 'STEM, Indigenous Education, Sustainability',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Engineering', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Fortescue Metals Group',
    industry: 'Mining & Energy',
    sector: 'Energy',
    size: 'Enterprise',
    location: 'Perth, WA',
    website: 'https://www.fmgl.com.au',
    fundingCapacity: 'High',
    csrFocus: 'STEM, Indigenous Employment, Sustainability',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Engineering', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Woodside Energy',
    industry: 'Energy',
    sector: 'Energy',
    size: 'Enterprise',
    location: 'Perth, WA',
    website: 'https://www.woodside.com',
    fundingCapacity: 'High',
    csrFocus: 'Engineering, Sustainability, Indigenous Programs',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Engineering', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Origin Energy',
    industry: 'Energy',
    sector: 'Energy',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.originenergy.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Renewable Energy, STEM, Sustainability',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Engineering', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'AGL Energy',
    industry: 'Energy',
    sector: 'Energy',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.agl.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Renewable Energy, Community, Sustainability',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'EnergyAustralia',
    industry: 'Energy',
    sector: 'Energy',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.energyaustralia.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Renewable Energy, STEM Education, Sustainability',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Sustainability']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Suncorp Group',
    industry: 'Insurance & Finance',
    sector: 'Finance',
    size: 'Enterprise',
    location: 'Brisbane, QLD',
    website: 'https://www.suncorp.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Community Education, Risk Management, Resilience',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Insurance Australia Group',
    industry: 'Insurance',
    sector: 'Finance',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.iag.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Community, Disaster Relief, Youth Programs',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development', 'Health']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Macquarie Group',
    industry: 'Finance',
    sector: 'Finance',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.macquarie.com',
    fundingCapacity: 'High',
    csrFocus: 'Education, Indigenous Programs, Community',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development', 'Intelligence']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Cisco Systems Australia',
    industry: 'Technology',
    sector: 'Software & Services',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.cisco.com/c/en_au/',
    fundingCapacity: 'High',
    csrFocus: 'Networking Education, Tech Skills, Innovation',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Future of Communication']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'IBM Australia',
    industry: 'Technology',
    sector: 'Software & Services',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.ibm.com/au-en',
    fundingCapacity: 'High',
    csrFocus: 'STEM, Tech Skills, Innovation',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Intelligence']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Oracle Australia',
    industry: 'Technology',
    sector: 'Software & Services',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.oracle.com/au/',
    fundingCapacity: 'High',
    csrFocus: 'Tech Education, Database Skills, Cloud',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Intelligence']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Audi Australia',
    industry: 'Automotive',
    sector: 'Automotive',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.audi.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Sustainable Mobility, Engineering, Education',
    btsPrograms: JSON.stringify(['GenIUS', 'Engineering', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Tesla Australia',
    industry: 'Automotive',
    sector: 'Automotive',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.tesla.com/au',
    fundingCapacity: 'High',
    csrFocus: 'Sustainable Transportation, Innovation, Engineering',
    btsPrograms: JSON.stringify(['GenIUS', 'Engineering', 'Sustainability', 'AI Academy']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'BMW Australia',
    industry: 'Automotive',
    sector: 'Automotive',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.bmw.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Sustainable Mobility, Engineering, Innovation',
    btsPrograms: JSON.stringify(['GenIUS', 'Engineering', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Ford Australia',
    industry: 'Automotive',
    sector: 'Automotive',
    size: 'Enterprise',
    location: 'Geelong, VIC',
    website: 'https://www.ford.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Engineering, Manufacturing, Sustainability',
    btsPrograms: JSON.stringify(['GenIUS', 'Engineering', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Toyota Australia',
    industry: 'Automotive',
    sector: 'Automotive',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.toyota.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Sustainable Transportation, Engineering, Education',
    btsPrograms: JSON.stringify(['GenIUS', 'Engineering', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Westfield Group',
    industry: 'Real Estate',
    sector: 'Real Estate',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.westfield.com',
    fundingCapacity: 'High',
    csrFocus: 'Community Development, Employment, Sustainability',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Lend Lease Group',
    industry: 'Real Estate & Construction',
    sector: 'Real Estate',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.lendlease.com',
    fundingCapacity: 'High',
    csrFocus: 'Sustainability, Urban Development, Skills',
    btsPrograms: JSON.stringify(['Engineering', 'Career Development', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'AMP Limited',
    industry: 'Finance',
    sector: 'Finance',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.amp.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Financial Wellbeing, Community, Youth',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development', 'Health']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Metcash Trading',
    industry: 'Wholesale & Retail',
    sector: 'Retail',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.metcash.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Community, Employment, Sustainability',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Qantas Airways',
    industry: 'Aviation',
    sector: 'Transportation',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.qantas.com.au',
    fundingCapacity: 'High',
    csrFocus: 'STEM, Indigenous Programs, Sustainability',
    btsPrograms: JSON.stringify(['Engineering', 'Career Development', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Virgin Australia',
    industry: 'Aviation',
    sector: 'Transportation',
    size: 'Enterprise',
    location: 'Brisbane, QLD',
    website: 'https://www.virginaustralia.com',
    fundingCapacity: 'High',
    csrFocus: 'Community, Employment, Sustainability',
    btsPrograms: JSON.stringify(['Engineering', 'Career Development', 'Sustainability']),
    tier: 1,
    isReal: true,
  },
  {
    name: 'Transurban Group',
    industry: 'Infrastructure',
    sector: 'Infrastructure',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.transurban.com',
    fundingCapacity: 'High',
    csrFocus: 'Community, Sustainability, Safety',
    btsPrograms: JSON.stringify(['Engineering', 'Career Development', 'Sustainability']),
    tier: 1,
    isReal: true,
  },

  // TIER 2: ASX 51-150 Companies
  {
    name: 'Ramsay Health Care',
    industry: 'Healthcare',
    sector: 'Healthcare',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.ramsayhealth.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Health Education, Community Health, Workforce',
    btsPrograms: JSON.stringify(['Health', 'Job Readiness', 'Career Development']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Sonic Healthcare',
    industry: 'Healthcare',
    sector: 'Healthcare',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.sonichealthcare.com',
    fundingCapacity: 'High',
    csrFocus: 'Health Literacy, Pathology Education, Community',
    btsPrograms: JSON.stringify(['Health', 'Career Development']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'HealthCare Australia',
    industry: 'Healthcare',
    sector: 'Healthcare',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.hc.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Aged Care, Community Health, Education',
    btsPrograms: JSON.stringify(['Health', 'Career Development']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Crown Resorts',
    industry: 'Entertainment & Hospitality',
    sector: 'Entertainment',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.crownresorts.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Community, Employment, Responsible Gaming',
    btsPrograms: JSON.stringify(['Career Development', 'Job Readiness']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Tabcorp Holdings',
    industry: 'Entertainment & Betting',
    sector: 'Entertainment',
    size: 'Large',
    location: 'Sydney, NSW',
    website: 'https://www.tabcorp.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Community, Responsible Gambling, Education',
    btsPrograms: JSON.stringify(['Career Development', 'Community']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Aristocrat Leisure',
    industry: 'Entertainment',
    sector: 'Entertainment',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.aristocratleisure.com',
    fundingCapacity: 'High',
    csrFocus: 'STEM, Innovation, Community',
    btsPrograms: JSON.stringify(['GenIUS', 'AI Academy', 'Career Development']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'James Hardie Industries',
    industry: 'Building Materials',
    sector: 'Manufacturing',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.jameshardie.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Engineering, Safety, Sustainability',
    btsPrograms: JSON.stringify(['Engineering', 'Sustainability', 'Career Development']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Bluescope Steel',
    industry: 'Manufacturing',
    sector: 'Manufacturing',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.bluescopesteel.com',
    fundingCapacity: 'Medium',
    csrFocus: 'STEM, Engineering, Sustainability',
    btsPrograms: JSON.stringify(['Engineering', 'Sustainability', 'GenIUS']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Amcor Limited',
    industry: 'Packaging',
    sector: 'Manufacturing',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.amcor.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Sustainability, Circular Economy, Innovation',
    btsPrograms: JSON.stringify(['Engineering', 'Sustainability', 'AI Academy']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Brambles Limited',
    industry: 'Supply Chain',
    sector: 'Logistics',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.brambles.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Sustainability, Circular Economy, Community',
    btsPrograms: JSON.stringify(['Sustainability', 'Career Development']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Seven West Media',
    industry: 'Media & Entertainment',
    sector: 'Media',
    size: 'Large',
    location: 'Perth, WA',
    website: 'https://www.sevenwestmedia.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Media Literacy, Community Stories, Education',
    btsPrograms: JSON.stringify(['Future of Communication', 'Career Development']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Nine Entertainment',
    industry: 'Media & Entertainment',
    sector: 'Media',
    size: 'Large',
    location: 'Sydney, NSW',
    website: 'https://www.9entertainment.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Media, Digital Literacy, Community',
    btsPrograms: JSON.stringify(['Future of Communication', 'AI Academy']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Seek Limited',
    industry: 'Employment',
    sector: 'Technology',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.seekinc.com',
    fundingCapacity: 'High',
    csrFocus: 'Employment, Skills, Career Development',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development', 'AI Academy']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'REA Group',
    industry: 'Real Estate Technology',
    sector: 'Technology',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.rea-group.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Real Estate Education, Community, Tech',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Future of Communication']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'ASX Limited',
    industry: 'Finance',
    sector: 'Finance',
    size: 'Large',
    location: 'Sydney, NSW',
    website: 'https://www.asx.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Financial Literacy, Market Education, Community',
    btsPrograms: JSON.stringify(['Intelligence', 'Career Development']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Perpetual Limited',
    industry: 'Finance',
    sector: 'Finance',
    size: 'Large',
    location: 'Sydney, NSW',
    website: 'https://www.perpetual.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Financial Literacy, Community, Indigenous Programs',
    btsPrograms: JSON.stringify(['Career Development', 'Financial Literacy']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Scentre Group',
    industry: 'Real Estate',
    sector: 'Real Estate',
    size: 'Large',
    location: 'Sydney, NSW',
    website: 'https://www.scentre.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Community, Employment, Diversity',
    btsPrograms: JSON.stringify(['Career Development', 'Job Readiness']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Stockland Group',
    industry: 'Real Estate',
    sector: 'Real Estate',
    size: 'Large',
    location: 'Sydney, NSW',
    website: 'https://www.stockland.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Community, Sustainability, Employment',
    btsPrograms: JSON.stringify(['Sustainability', 'Career Development', 'Community']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Vicinity Centres',
    industry: 'Real Estate',
    sector: 'Real Estate',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.vicinitycentres.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Community, Local Development, Employment',
    btsPrograms: JSON.stringify(['Career Development', 'Community']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Mirvac Group',
    industry: 'Real Estate & Development',
    sector: 'Real Estate',
    size: 'Large',
    location: 'Sydney, NSW',
    website: 'https://www.mirvac.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Community, Sustainability, Urban Development',
    btsPrograms: JSON.stringify(['Sustainability', 'Career Development']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Dexus',
    industry: 'Real Estate',
    sector: 'Real Estate',
    size: 'Large',
    location: 'Sydney, NSW',
    website: 'https://www.dexus.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Community, Sustainability, Green Buildings',
    btsPrograms: JSON.stringify(['Sustainability', 'Engineering']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Charter Hall Group',
    industry: 'Real Estate',
    sector: 'Real Estate',
    size: 'Large',
    location: 'Sydney, NSW',
    website: 'https://www.charterhall.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Community, Sustainability, Social',
    btsPrograms: JSON.stringify(['Sustainability', 'Community']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Centennial Coal',
    industry: 'Mining',
    sector: 'Energy',
    size: 'Large',
    location: 'Sydney, NSW',
    website: 'https://www.centennialcoal.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'STEM, Community, Indigenous Programs',
    btsPrograms: JSON.stringify(['Engineering', 'Sustainability']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Orocobre Limited',
    industry: 'Mining',
    sector: 'Energy',
    size: 'Medium',
    location: 'Melbourne, VIC',
    website: 'https://www.orocobre.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Lithium Sustainability, Community, Indigenous',
    btsPrograms: JSON.stringify(['Sustainability', 'Engineering']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Resolute Mining',
    industry: 'Mining',
    sector: 'Energy',
    size: 'Large',
    location: 'Perth, WA',
    website: 'https://www.resolute.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Gold Mining, Community, Indigenous Programs',
    btsPrograms: JSON.stringify(['Engineering', 'Sustainability']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Newcrest Mining',
    industry: 'Mining',
    sector: 'Energy',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.newcrest.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Mining, STEM, Sustainability, Community',
    btsPrograms: JSON.stringify(['Engineering', 'Sustainability', 'STEM']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Evolution Mining',
    industry: 'Mining',
    sector: 'Energy',
    size: 'Large',
    location: 'Brisbane, QLD',
    website: 'https://www.evolutionmining.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Gold Mining, Community, Indigenous Programs',
    btsPrograms: JSON.stringify(['Engineering', 'Community']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'IGO Limited',
    industry: 'Mining',
    sector: 'Energy',
    size: 'Large',
    location: 'Perth, WA',
    website: 'https://www.igo.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Lithium & Nickel, Sustainability, Community',
    btsPrograms: JSON.stringify(['Engineering', 'Sustainability']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Ramelius Resources',
    industry: 'Mining',
    sector: 'Energy',
    size: 'Medium',
    location: 'Perth, WA',
    website: 'https://www.rameliusresources.com.au',
    fundingCapacity: 'Low',
    csrFocus: 'Gold Mining, Indigenous Programs, Community',
    btsPrograms: JSON.stringify(['Engineering', 'Community']),
    tier: 3,
    isReal: true,
  },
  {
    name: 'Glanbia Ireland',
    industry: 'Food & Beverage',
    sector: 'Consumer Goods',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.glanbia.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Nutrition, Sustainability, Education',
    btsPrograms: JSON.stringify(['Health', 'Sustainability']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Boral Limited',
    industry: 'Building Materials',
    sector: 'Manufacturing',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.boral.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Engineering, Sustainability, Community',
    btsPrograms: JSON.stringify(['Engineering', 'Sustainability']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Smurfit Westrock Australia',
    industry: 'Packaging & Containers',
    sector: 'Manufacturing',
    size: 'Large',
    location: 'Sydney, NSW',
    website: 'https://www.smurfitkappa.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Sustainability, Circular Economy, Recycling',
    btsPrograms: JSON.stringify(['Sustainability', 'Engineering']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Incitec Pivot',
    industry: 'Chemicals & Fertilizer',
    sector: 'Manufacturing',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.incitecpivot.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Agriculture, Sustainability, STEM',
    btsPrograms: JSON.stringify(['Engineering', 'Sustainability', 'STEM']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Endeavour Group',
    industry: 'Retail',
    sector: 'Retail',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.endeavour.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Alcohol Responsibility, Community, Employment',
    btsPrograms: JSON.stringify(['Career Development', 'Health']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Wesfarmers Limited',
    industry: 'Retail & Conglomerate',
    sector: 'Retail',
    size: 'Enterprise',
    location: 'Perth, WA',
    website: 'https://www.wesfarmers.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Community, Diversity, Employment, Sustainability',
    btsPrograms: JSON.stringify(['Career Development', 'Job Readiness', 'Sustainability']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'JB Hi-Fi',
    industry: 'Retail',
    sector: 'Retail',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.jbhifi.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Technology, Community, Employment',
    btsPrograms: JSON.stringify(['Future of Communication', 'Career Development']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Rebel Group',
    industry: 'Retail',
    sector: 'Retail',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.rebel.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Sports, Health, Community, Indigenous',
    btsPrograms: JSON.stringify(['Health', 'Community']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Cotton On Group',
    industry: 'Retail',
    sector: 'Retail',
    size: 'Large',
    location: 'Geelong, VIC',
    website: 'https://www.cottonon.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Ethical Fashion, Sustainability, Community',
    btsPrograms: JSON.stringify(['Sustainability', 'Career Development']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Mitre 10 Australia',
    industry: 'Retail',
    sector: 'Retail',
    size: 'Large',
    location: 'Sydney, NSW',
    website: 'https://www.mitre10.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Community Projects, Employment, DIY Skills',
    btsPrograms: JSON.stringify(['Career Development', 'Engineering']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Bunnings Warehouse',
    industry: 'Retail',
    sector: 'Retail',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.bunnings.com.au',
    fundingCapacity: 'High',
    csrFocus: 'Community Projects, Employment, DIY, Sustainability',
    btsPrograms: JSON.stringify(['Career Development', 'Engineering', 'Sustainability']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Spotlight Group',
    industry: 'Retail',
    sector: 'Retail',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.spotlightgroup.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Creative Education, Community, Diversity',
    btsPrograms: JSON.stringify(['Future of Communication', 'Career Development']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Kmart Australia',
    industry: 'Retail',
    sector: 'Retail',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.kmart.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Affordable Living, Community, Employment',
    btsPrograms: JSON.stringify(['Career Development', 'Community']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Target Australia',
    industry: 'Retail',
    sector: 'Retail',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.target.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Community, Employment, Sustainability',
    btsPrograms: JSON.stringify(['Career Development', 'Sustainability']),
    tier: 2,
    isReal: true,
  },

  // TIER 3: ASX 151-300 Companies (Sample - Real companies)
  {
    name: 'Altona Mining',
    industry: 'Mining',
    sector: 'Energy',
    size: 'Medium',
    location: 'Brisbane, QLD',
    website: 'https://www.altonamining.com',
    fundingCapacity: 'Low',
    csrFocus: 'Mining, Sustainability, Community',
    btsPrograms: JSON.stringify(['Engineering', 'Sustainability']),
    tier: 3,
    isReal: true,
  },
  {
    name: 'Sandfire Resources',
    industry: 'Mining',
    sector: 'Energy',
    size: 'Medium',
    location: 'Perth, WA',
    website: 'https://www.sandfire.com.au',
    fundingCapacity: 'Low',
    csrFocus: 'Copper Mining, Sustainability, Indigenous',
    btsPrograms: JSON.stringify(['Engineering', 'Community']),
    tier: 3,
    isReal: true,
  },
  {
    name: 'Dacian Gold',
    industry: 'Mining',
    sector: 'Energy',
    size: 'Small',
    location: 'Perth, WA',
    website: 'https://www.daciangold.com.au',
    fundingCapacity: 'Low',
    csrFocus: 'Gold Mining, Community, Indigenous',
    btsPrograms: JSON.stringify(['Engineering']),
    tier: 3,
    isReal: true,
  },
  {
    name: 'Avebury Metals',
    industry: 'Mining',
    sector: 'Energy',
    size: 'Small',
    location: 'Melbourne, VIC',
    website: 'https://www.averbatemetals.com',
    fundingCapacity: 'Low',
    csrFocus: 'Mining, Sustainability, Community',
    btsPrograms: JSON.stringify(['Engineering']),
    tier: 3,
    isReal: true,
  },
  {
    name: 'Acubis Group',
    industry: 'Technology',
    sector: 'Technology',
    size: 'Medium',
    location: 'Melbourne, VIC',
    website: 'https://www.acubis.com.au',
    fundingCapacity: 'Low',
    csrFocus: 'Enterprise Software, Innovation',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS']),
    tier: 3,
    isReal: true,
  },
  {
    name: 'Atlassian (founded in Australia)',
    industry: 'Technology',
    sector: 'Software & Services',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.atlassian.com',
    fundingCapacity: 'High',
    csrFocus: 'Tech Education, Open Source, Community',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Future of Communication']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'WiseTech Global',
    industry: 'Technology',
    sector: 'Software & Services',
    size: 'Enterprise',
    location: 'Sydney, NSW',
    website: 'https://www.wisetechglobal.com',
    fundingCapacity: 'High',
    csrFocus: 'Logistics Software, Education, Innovation',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Nearmap Limited',
    industry: 'Technology',
    sector: 'Software & Services',
    size: 'Medium',
    location: 'Melbourne, VIC',
    website: 'https://www.nearmap.com',
    fundingCapacity: 'Medium',
    csrFocus: 'Geospatial Technology, Innovation, Education',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Engineering']),
    tier: 3,
    isReal: true,
  },
  {
    name: 'Afterpay Limited',
    industry: 'Fintech',
    sector: 'Finance',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.afterpay.com',
    fundingCapacity: 'High',
    csrFocus: 'Financial Inclusion, Youth Engagement, Fintech',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Intelligence']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Zip Company',
    industry: 'Fintech',
    sector: 'Finance',
    size: 'Medium',
    location: 'Sydney, NSW',
    website: 'https://www.zip.co',
    fundingCapacity: 'Medium',
    csrFocus: 'Financial Inclusion, Youth, Education',
    btsPrograms: JSON.stringify(['AI Academy', 'Intelligence']),
    tier: 3,
    isReal: true,
  },
  {
    name: 'Xero Limited',
    industry: 'Accounting Software',
    sector: 'Software & Services',
    size: 'Enterprise',
    location: 'Melbourne, VIC',
    website: 'https://www.xero.com',
    fundingCapacity: 'High',
    csrFocus: 'Small Business Education, Financial Literacy',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS', 'Intelligence']),
    tier: 2,
    isReal: true,
  },
  {
    name: 'Sentia',
    industry: 'Technology',
    sector: 'Cloud Services',
    size: 'Medium',
    location: 'Melbourne, VIC',
    website: 'https://www.sentia.com',
    fundingCapacity: 'Low',
    csrFocus: 'Cloud Technology, Innovation',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS']),
    tier: 3,
    isReal: true,
  },

  // TIER 4: Regional, SME and Emerging Companies (Sample)
  {
    name: 'Geelong Chamber of Commerce',
    industry: 'Business Organization',
    sector: 'Services',
    size: 'Small',
    location: 'Geelong, VIC',
    website: 'https://www.geelongchamber.com.au',
    fundingCapacity: 'Low',
    csrFocus: 'Local Business, Community, Education',
    btsPrograms: JSON.stringify(['Career Development', 'Business Skills']),
    tier: 4,
    isReal: true,
  },
  {
    name: 'Melbourne Tech Hub',
    industry: 'Technology Hub',
    sector: 'Technology',
    size: 'Small',
    location: 'Melbourne, VIC',
    website: 'https://www.melbtech.com.au',
    fundingCapacity: 'Low',
    csrFocus: 'Tech Innovation, Startup Support, Education',
    btsPrograms: JSON.stringify(['AI Academy', 'GenIUS']),
    tier: 4,
    isReal: true,
  },
  {
    name: 'Brimbank Chamber of Commerce',
    industry: 'Business Organization',
    sector: 'Services',
    size: 'Small',
    location: 'Brimbank, VIC',
    website: 'https://www.brimbankcc.com.au',
    fundingCapacity: 'Low',
    csrFocus: 'Local Business Support, Community, Youth',
    btsPrograms: JSON.stringify(['Career Development', 'Community']),
    tier: 4,
    isReal: true,
  },
  {
    name: 'Western Melbourne Manufacturing Alliance',
    industry: 'Business Association',
    sector: 'Manufacturing',
    size: 'Small',
    location: 'Melbourne, VIC',
    website: 'https://www.wmma.org.au',
    fundingCapacity: 'Low',
    csrFocus: 'Manufacturing Support, STEM, Skills',
    btsPrograms: JSON.stringify(['Engineering', 'STEM', 'Career Development']),
    tier: 4,
    isReal: true,
  },
  {
    name: 'Sustainability Victoria',
    industry: 'Government Agency',
    sector: 'Government',
    size: 'Medium',
    location: 'Melbourne, VIC',
    website: 'https://www.sustainability.vic.gov.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Sustainability, Education, Innovation',
    btsPrograms: JSON.stringify(['Sustainability', 'Innovation']),
    tier: 4,
    isReal: true,
  },
  {
    name: 'Transport Workers Union Victoria',
    industry: 'Union Organization',
    sector: 'Services',
    size: 'Small',
    location: 'Melbourne, VIC',
    website: 'https://www.twuv.org.au',
    fundingCapacity: 'Low',
    csrFocus: 'Worker Skills, Education, Community',
    btsPrograms: JSON.stringify(['Career Development', 'Job Readiness']),
    tier: 4,
    isReal: true,
  },
  {
    name: 'Australian Manufacturing Forum',
    industry: 'Industry Organization',
    sector: 'Manufacturing',
    size: 'Small',
    location: 'Melbourne, VIC',
    website: 'https://www.amf.org.au',
    fundingCapacity: 'Low',
    csrFocus: 'Manufacturing, STEM, Skills Development',
    btsPrograms: JSON.stringify(['Engineering', 'STEM', 'Career Development']),
    tier: 4,
    isReal: true,
  },
  {
    name: 'Local Government Association of Victoria',
    industry: 'Government Organization',
    sector: 'Government',
    size: 'Medium',
    location: 'Melbourne, VIC',
    website: 'https://www.lgav.org.au',
    fundingCapacity: 'Low',
    csrFocus: 'Local Government, Community Development',
    btsPrograms: JSON.stringify(['Community', 'Career Development']),
    tier: 4,
    isReal: true,
  },
  {
    name: 'Migrant Resource Centre Victoria',
    industry: 'Community Organization',
    sector: 'Services',
    size: 'Medium',
    location: 'Melbourne, VIC',
    website: 'https://www.mrcv.org.au',
    fundingCapacity: 'Low',
    csrFocus: 'Migrant Integration, Education, Employment',
    btsPrograms: JSON.stringify(['Job Readiness', 'Career Development', 'Language']),
    tier: 4,
    isReal: true,
  },
  {
    name: 'Youth Affairs Council Victoria',
    industry: 'Youth Organization',
    sector: 'Services',
    size: 'Medium',
    location: 'Melbourne, VIC',
    website: 'https://www.yacvic.org.au',
    fundingCapacity: 'Low',
    csrFocus: 'Youth Engagement, Education, Community',
    btsPrograms: JSON.stringify(['Career Development', 'Health', 'Community']),
    tier: 4,
    isReal: true,
  },
  {
    name: 'Victorian Curriculum and Assessment Authority',
    industry: 'Education',
    sector: 'Education',
    size: 'Medium',
    location: 'Melbourne, VIC',
    website: 'https://www.vcaa.vic.edu.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Education Standards, Curriculum, Assessment',
    btsPrograms: JSON.stringify(['STEM', 'Education', 'Career Development']),
    tier: 4,
    isReal: true,
  },
  {
    name: 'Department of Jobs, Precincts and Regions',
    industry: 'Government',
    sector: 'Government',
    size: 'Large',
    location: 'Melbourne, VIC',
    website: 'https://www.djpr.vic.gov.au',
    fundingCapacity: 'High',
    csrFocus: 'Economic Development, Skills, Jobs',
    btsPrograms: JSON.stringify(['Career Development', 'Job Readiness', 'STEM']),
    tier: 4,
    isReal: true,
  },
  {
    name: 'Skills Victoria',
    industry: 'Education',
    sector: 'Education',
    size: 'Medium',
    location: 'Melbourne, VIC',
    website: 'https://www.skillsvictoria.com.au',
    fundingCapacity: 'Medium',
    csrFocus: 'Vocational Training, Skills Development',
    btsPrograms: JSON.stringify(['Career Development', 'Job Readiness']),
    tier: 4,
    isReal: true,
  },
];

async function seedAslCompanies() {
  console.log('🌱 Adding ASX and Australian companies...');
  let added = 0;
  let skipped = 0;

  for (const company of ASX_COMPANIES) {
    const existing = await prisma.company.findUnique({
      where: { name: company.name },
    });
    if (!existing) {
      await prisma.company.create({ data: company });
      added++;
    } else {
      skipped++;
    }
  }

  console.log(`✅ Added ${added} new companies (${skipped} already existed)`);
}

seedAslCompanies()
  .then(() => prisma.$disconnect())
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
