import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const BTS_PARTNERS = [
  {
    name: 'Partner name ',
    industry: 'Focus Area ',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Engagement Mode ',
    notes: 'Type: Partner Type  | Stage: Engagement Stage  | Mode: Engagement Mode  | Focus: Focus Area ',
    isReal: true,
  },
  {
    name: 'Melbourne Airport ',
    industry: 'Research & Evaluation',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: Primary Delivery Partner | Stage: Active  | Mode: Program Delivery | Focus: Research & Evaluation',
    isReal: true,
  },
  {
    name: 'PMY Technology Solutions',
    industry: 'Embedded Programs',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: Primary Delivery Partner | Stage: Active  | Mode: Program Delivery | Focus: Embedded Programs',
    isReal: true,
  },
  {
    name: 'Adobe',
    industry: 'Design Sprints',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Capability Building',
    notes: 'Type: External Partner | Stage: Aligned  | Mode: Capability Building | Focus: Design Sprints',
    isReal: true,
  },
  {
    name: 'LEGO Education',
    industry: 'Embedded Programs',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Active  | Mode: Program Delivery | Focus: Embedded Programs',
    isReal: true,
  },
  {
    name: 'Blackmagic Design ',
    industry: 'Future of Work',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Advisory | Focus: Future of Work',
    isReal: true,
  },
  {
    name: 'Canopy Creative',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Aligned  | Mode: Advisory | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'Australian Computer Society ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: Primary Delivery Partner | Stage: Aligned  | Mode: Advisory | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'Engineers Australia ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: Primary Delivery Partner | Stage: Aligned  | Mode: Advisory | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'Drone Racing Academy ',
    industry: 'Embedded Programs',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Embedded Programs',
    isReal: true,
  },
  {
    name: 'Halo Sports ',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Co‑Design | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'Asian Games ',
    industry: 'Future of Work',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Advisory | Focus: Future of Work',
    isReal: true,
  },
  {
    name: 'Melbourne Fashion Hub ',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: External Partner | Stage: Aligned  | Mode: Co‑Design | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'AGL',
    industry: 'Research & Evaluation',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: Grant‑Enabled Partner  | Stage: Exploring  | Mode: Advisory | Focus: Research & Evaluation',
    isReal: true,
  },
  {
    name: 'Red Cross',
    industry: 'Future of Work',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Capability Building',
    notes: 'Type: External Partner | Stage: Aligned  | Mode: Capability Building | Focus: Future of Work',
    isReal: true,
  },
  {
    name: 'Bridget Tehan ',
    industry: 'Future of Work',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Active  | Mode: Advisory | Focus: Future of Work',
    isReal: true,
  },
  {
    name: 'Engineers Without Borders',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: External Partner | Stage: Aligned  | Mode: Co‑Design | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'MRWA ',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: Primary Delivery Partner | Stage: Active  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'Greater Western Water',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: Primary Partner | Stage: Aligned  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'Dr Catherine Ball',
    industry: 'Embedded Programs',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Embedded Programs',
    isReal: true,
  },
  {
    name: 'Dr Ari Pinar',
    industry: 'Embedded Programs',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: External Partner | Stage: Active  | Mode: Co‑Design | Focus: Embedded Programs',
    isReal: true,
  },
  {
    name: 'Ai her Way ',
    industry: 'Future of Work',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: External Partner | Stage: Active  | Mode: Co‑Design | Focus: Future of Work',
    isReal: true,
  },
  {
    name: 'Bugbox ',
    industry: 'Future of Work',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: External Partner | Stage: Active  | Mode: Co‑Design | Focus: Future of Work',
    isReal: true,
  },
  {
    name: 'Collarts ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: External Partner | Stage: Strategic  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'Australian Sports Commission ',
    industry: 'Future of Work',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Aligned  | Mode: Advisory | Focus: Future of Work',
    isReal: true,
  },
  {
    name: 'Nanjin Educators',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Aligned  | Mode: Advisory | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'VU Visitor Economy',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: Internal Collaboration (VU) | Stage: Active  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'Mathworks ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'Lendlease',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'VU Hospitality and Events',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: Internal Collaboration (VU) | Stage: Active  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'Western Bulldogs ',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: Internal Collaboration (VU) | Stage: Active  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'VIDA',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Capability Building',
    notes: 'Type: Primary Partner | Stage: Aligned  | Mode: Capability Building | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'NBN',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Grant‑Enabled Partner  | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'Transit Buses',
    industry: 'Research & Evaluation',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Strategic  | Mode: Program Delivery | Focus: Research & Evaluation',
    isReal: true,
  },
  {
    name: 'Ventura Buses',
    industry: 'Research & Evaluation',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Strategic  | Mode: Program Delivery | Focus: Research & Evaluation',
    isReal: true,
  },
  {
    name: 'Movember',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: External Partner | Stage: Aligned  | Mode: Co‑Design | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'CoE Thriving Childhoods',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: Internal Collaboration (VU) | Stage: Exploring  | Mode: Co‑Design | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'DE Koorie Engagement ',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Co‑Design | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'VU Careers ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'DE Mental Health Reforms',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Co‑Design | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'VU WiT ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'Quest Watergardens ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'MTA',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Capability Building',
    notes: 'Type: External Partner | Stage: Aligned  | Mode: Capability Building | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'VU Cyber',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'STACK Infrarstructure ',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'VU Hive ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'VU WIL ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'LEAP',
    industry: 'Design Sprints',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Co‑Design | Focus: Design Sprints',
    isReal: true,
  },
  {
    name: 'Be More Butter',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'EBMpapst',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Co‑Design | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'ANU Cybernetics',
    industry: 'Teacher Capability',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: External Partner | Stage: Active  | Mode: Co‑Design | Focus: Teacher Capability',
    isReal: true,
  },
  {
    name: 'VU Project 110 ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'Wellbeing Distellery ',
    industry: 'Research & Evaluation',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Capability Building',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Capability Building | Focus: Research & Evaluation',
    isReal: true,
  },
  {
    name: 'Unanimas',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'Vans Australia ',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'VSSEC',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'Lander and Rogers ',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Co‑Design | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'Beyond Blue ',
    industry: 'Research & Evaluation',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Capability Building',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Capability Building | Focus: Research & Evaluation',
    isReal: true,
  },
  {
    name: 'AIIW',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'VU FYC ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'VU Research ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'Kaleida Group ',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'VUI Sustainable Industries',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'VU Digital ',
    industry: 'Pathways & Progression',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Pathway Alignment',
    notes: 'Type: Internal Collaboration (VU) | Stage: Aligned  | Mode: Pathway Alignment | Focus: Pathways & Progression',
    isReal: true,
  },
  {
    name: 'Seek Investments ',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Capability Building',
    notes: 'Type: External Partner | Stage: Aligned  | Mode: Capability Building | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'Inventium',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'First Lego League',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'Drone It',
    industry: 'Embedded Programs',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Embedded Programs',
    isReal: true,
  },
  {
    name: 'Vic Screen ',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'Aus Screen',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'Google',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Program Delivery',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Program Delivery | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'SXSW Sydney ',
    industry: 'Industry Projects',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Co‑Design',
    notes: 'Type: External Partner | Stage: Exploring  | Mode: Co‑Design | Focus: Industry Projects',
    isReal: true,
  },
  {
    name: 'RMIT',
    industry: 'General',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Exploring | Mode: Advisory | Focus: General',
    isReal: true,
  },
  {
    name: 'Community Consulting ',
    industry: 'General',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Exploring | Mode: Advisory | Focus: General',
    isReal: true,
  },
  {
    name: 'Omni One ',
    industry: 'General',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Exploring | Mode: Advisory | Focus: General',
    isReal: true,
  },
  {
    name: 'Raytracer',
    industry: 'General',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Exploring | Mode: Advisory | Focus: General',
    isReal: true,
  },
  {
    name: 'IGEA',
    industry: 'General',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Exploring | Mode: Advisory | Focus: General',
    isReal: true,
  },
  {
    name: 'LLEN',
    industry: 'General',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Exploring | Mode: Advisory | Focus: General',
    isReal: true,
  },
  {
    name: 'AWE Network ',
    industry: 'General',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Exploring | Mode: Advisory | Focus: General',
    isReal: true,
  },
  {
    name: 'Lucie Impala ',
    industry: 'General',
    sector: 'Strategic Partner',
    size: 'Enterprise',
    location: 'Victoria, Australia',
    fundingCapacity: 'High',
    csrFocus: 'Advisory',
    notes: 'Type: External Partner | Stage: Exploring | Mode: Advisory | Focus: General',
    isReal: true,
  },
];

async function seedPartners() {
  console.log('🌱 Adding BTS strategic partners...');
  let added = 0;

  for (const partner of BTS_PARTNERS) {
    const existing = await prisma.company.findUnique({
      where: { name: partner.name },
    });
    if (!existing) {
      await prisma.company.create({ data: partner });
      added++;
    }
  }

  console.log(`✅ Added ${added} strategic partners`);
}

seedPartners()
  .then(() => prisma.$disconnect())
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
